version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=books
      - POSTGRES_PASSWORD=qwe123asd
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"

  nginx:
    build: ./docker/nginx
    volumes:
      - ./source:/var/www:cached
      - ./docker/nginx/sites/default.conf:/etc/nginx/sites-available/default.conf
      - ./docker/logs/nginx/:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_OPCACHE=true
    volumes:
      - ./source:/var/www:cached
    depends_on:
      - postgres
    expose:
      - "9000"

  php-cli:
    build:
      context: ./docker/php-cli
      args:
        - INSTALL_XDEBUG=true
    volumes:
      - ./source:/var/www:cached
    working_dir: /var/www
    depends_on:
      - postgres

  node:
    image: node:10-alpine
    volumes:
      - ./source:/var/www
    command: yarn encore production --watch
    working_dir: /var/www